# Generated by Django 4.2.11 on 2024-05-25 23:12

import DreamTravelapp.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aerolinea',
            fields=[
                ('id_aerolinea', models.AutoField(primary_key=True, serialize=False)),
                ('nombreAerolinea', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Aerolinea',
                'verbose_name_plural': 'Aerolineas',
                'db_table': 'aerolinea',
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id_localidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombreLocalidad', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Localidade',
                'verbose_name_plural': 'Localidades',
                'db_table': 'localidad',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodoPago', models.AutoField(primary_key=True, serialize=False)),
                ('nombrePago', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Metodos De Pago',
                'verbose_name_plural': 'Metodos de pagos',
                'db_table': 'metodo_pago',
            },
        ),
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id_obraSocial', models.AutoField(primary_key=True, serialize=False)),
                ('nombreObraSocial', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Obras Sociale',
                'verbose_name_plural': 'Obras Sociales',
                'db_table': 'obra_social',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('apellido_usuario', models.CharField(max_length=100)),
                ('passw', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(8)])),
                ('telefono', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('id_localidad', models.ForeignKey(db_column='id_localidad', on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.localidad')),
                ('id_metodoPago', models.ForeignKey(db_column='id_metodoPago', on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.metodopago')),
                ('id_obraSocial', models.ForeignKey(db_column='id_obraSocial', on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.obrasocial')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Destinos',
            fields=[
                ('id_destino', models.AutoField(primary_key=True, serialize=False)),
                ('nombreDestino', models.CharField(max_length=150)),
                ('precioDestino', models.DecimalField(decimal_places=2, max_digits=12, validators=[DreamTravelapp.models.positive_price_validator])),
                ('fecha_salida', models.DateTimeField()),
                ('cantidadDisponible', models.IntegerField(default=12, validators=[DreamTravelapp.models.positive_viaje_validator])),
                ('id_aerolinea', models.ForeignKey(db_column='id_aerolinea', on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.aerolinea')),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.categorias')),
                ('id_metodoPago', models.ForeignKey(db_column='id_metodoPago', on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.metodopago')),
            ],
            options={
                'verbose_name': 'Destino',
                'verbose_name_plural': 'Destinos',
                'db_table': 'destinos',
            },
        ),
    ]
