# Generated by Django 4.2.11 on 2024-05-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamTravelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='apellido_usuario',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre_usuario',
            field=models.CharField(max_length=100),
        ),
    ]
