# Generated by Django 4.2.11 on 2024-05-13 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DreamTravelapp', '0002_alter_usuarios_apellido_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aerolinea',
            options={'verbose_name': 'Aerolinea'},
        ),
        migrations.AlterModelOptions(
            name='categorias',
            options={'verbose_name': 'Categoria'},
        ),
        migrations.AlterModelOptions(
            name='localidad',
            options={'verbose_name': 'Localidade'},
        ),
        migrations.AlterModelOptions(
            name='metodopago',
            options={'verbose_name': 'Metodos De Pago'},
        ),
        migrations.AlterModelOptions(
            name='obrasocial',
            options={'verbose_name': 'Obras Sociale'},
        ),
        migrations.RemoveField(
            model_name='destinos',
            name='id_aerolinea',
        ),
        migrations.RemoveField(
            model_name='destinos',
            name='id_categoria',
        ),
        migrations.RemoveField(
            model_name='destinos',
            name='id_metodoPago',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='id_metodoPago',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='id_obraSocial',
        ),
    ]
