# Generated by Django 5.0.6 on 2024-05-13 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DreamTravelapp', '0003_alter_aerolinea_options_alter_categorias_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='id_localidad',
        ),
    ]
