# Generated by Django 5.0.6 on 2024-05-13 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamTravelapp', '0004_remove_usuarios_id_localidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='id_localidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.localidad'),
        ),
    ]
