# Generated by Django 5.0.6 on 2024-05-13 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamTravelapp', '0006_remove_usuarios_id_localidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aerolinea',
            options={'verbose_name': 'Aerolinea', 'verbose_name_plural': 'Aerolineas'},
        ),
        migrations.AlterModelOptions(
            name='categorias',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='destinos',
            options={'verbose_name': 'Destino', 'verbose_name_plural': 'Destinos'},
        ),
        migrations.AlterModelOptions(
            name='localidad',
            options={'verbose_name': 'Localidade', 'verbose_name_plural': 'Localidades'},
        ),
        migrations.AlterModelOptions(
            name='metodopago',
            options={'verbose_name': 'Metodos De Pago', 'verbose_name_plural': 'Metodos de pagos'},
        ),
        migrations.AlterModelOptions(
            name='obrasocial',
            options={'verbose_name': 'Obras Sociale', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='destinos',
            name='id_aerolinea',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.aerolinea'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinos',
            name='id_categoria',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.categorias'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinos',
            name='id_metodoPago',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.metodopago'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='id_localidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.localidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='id_obraSocial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.obrasocial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='metodoPago',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.metodopago'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aerolinea',
            name='id_aerolinea',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
