# Generated by Django 5.0.6 on 2024-05-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamTravelapp', '0007_alter_aerolinea_options_alter_categorias_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obrasocial',
            options={'verbose_name': 'Obras Sociale', 'verbose_name_plural': 'Obras Sociales'},
        ),
        migrations.AlterField(
            model_name='aerolinea',
            name='id_aerolinea',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
