# Generated by Django 5.0.6 on 2024-05-14 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DreamTravelapp', '0008_alter_obrasocial_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='metodoPago',
            new_name='id_metodoPago',
        ),
    ]
