# Generated by Django 4.2.11 on 2024-05-29 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DreamTravelapp', '0009_rename_metodopago_usuarios_id_metodopago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinos',
            old_name='cantidadDisponible',
            new_name='cantidad_Disponible',
        ),
        migrations.RenameField(
            model_name='destinos',
            old_name='nombreDestino',
            new_name='nombre_Destino',
        ),
        migrations.RenameField(
            model_name='destinos',
            old_name='precioDestino',
            new_name='precio_Destino',
        ),
        migrations.RemoveField(
            model_name='destinos',
            name='id_aerolinea',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='id_localidad',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='id_obraSocial',
        ),
        migrations.AddField(
            model_name='destinos',
            name='descripcion',
            field=models.TextField(default='descripcion'),
        ),
        migrations.AddField(
            model_name='destinos',
            name='image',
            field=models.TextField(default='imagen'),
        ),
        migrations.AlterField(
            model_name='destinos',
            name='id_categoria',
            field=models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.categorias'),
        ),
        migrations.AlterField(
            model_name='destinos',
            name='id_metodoPago',
            field=models.ForeignKey(db_column='id_metodoPago', on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.metodopago'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id_metodoPago',
            field=models.ForeignKey(db_column='id_metodoPago', on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.metodopago'),
        ),
        migrations.DeleteModel(
            name='Aerolinea',
        ),
        migrations.DeleteModel(
            name='Localidad',
        ),
        migrations.DeleteModel(
            name='ObraSocial',
        ),
    ]
