# Generated by Django 4.2.11 on 2024-05-29 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DreamTravelapp', '0009_rename_metodopago_usuarios_id_metodopago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinos',
            name='id_aerolinea',
            field=models.ForeignKey(db_column='id_aerolinea', on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.aerolinea'),
        ),
        migrations.AlterField(
            model_name='destinos',
            name='id_categoria',
            field=models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.categorias'),
        ),
        migrations.AlterField(
            model_name='destinos',
            name='id_metodoPago',
            field=models.ForeignKey(db_column='id_metodoPago', on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.metodopago'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id_localidad',
            field=models.ForeignKey(db_column='id_localidad', on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.localidad'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id_metodoPago',
            field=models.ForeignKey(db_column='id_metodoPago', on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.metodopago'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id_obraSocial',
            field=models.ForeignKey(db_column='id_obraSocial', on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.obrasocial'),
        ),
    ]
