# Generated by Django 4.2.11 on 2024-05-29 00:29

import DreamTravelapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DreamTravelapp', '0010_rename_cantidaddisponible_destinos_cantidad_disponible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id_nosotros', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_apellido', models.CharField(max_length=100)),
                ('rol', models.CharField(default='desarrollador', max_length=100)),
                ('github', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('imagen', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Nosotros',
                'verbose_name_plural': 'Nosotros',
                'db_table': 'nosotros',
            },
        ),
        migrations.AddField(
            model_name='usuarios',
            name='rol',
            field=models.CharField(default='usuario', max_length=100),
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=0, max_digits=3, validators=[DreamTravelapp.models.positive_price_validator])),
                ('id_destino', models.ForeignKey(db_column='id_destino', on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.destinos')),
                ('id_metodoPago', models.ForeignKey(db_column='id_metodoPago', on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.metodopago')),
            ],
        ),
    ]
