# Generated by Django 4.2.11 on 2024-06-03 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DreamTravelapp', '0011_nosotros_usuarios_rol_carrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(default='usuario', max_length=100)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'roles',
                'db_table': 'rol',
            },
        ),
        migrations.AlterModelOptions(
            name='categorias',
            options={},
        ),
        migrations.RemoveField(
            model_name='nosotros',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='rol',
        ),
        migrations.AlterModelTable(
            name='categorias',
            table=None,
        ),
        migrations.AddField(
            model_name='nosotros',
            name='id_rol',
            field=models.ForeignKey(db_column='id_rol', default='1', on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.rol'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='id_rol',
            field=models.ForeignKey(db_column='id_rol', default='1', on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.rol'),
        ),
    ]
