# Generated by Django 4.2.11 on 2024-06-04 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DreamTravelapp', '0013_alter_rol_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='id_rol',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='nombre_rol',
            field=models.ForeignKey(db_column='nombre_rol', default='Usuario', on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.rol'),
        ),
        migrations.AlterField(
            model_name='nosotros',
            name='id_rol',
            field=models.ForeignKey(db_column='id_rol', default=3, on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.rol'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre_rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Usuario', 'Usuario'), ('Full Stack', 'Full Stack')], default='Usuario', max_length=100),
        ),
    ]
