# Generated by Django 4.2.11 on 2024-06-04 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DreamTravelapp', '0014_alter_rol_options_remove_usuarios_id_rol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='nombre_rol',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='id_rol',
            field=models.ForeignKey(db_column='id_rol', default='1', on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.rol'),
        ),
    ]
