# Generated by Django 4.2.11 on 2024-06-05 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DreamTravelapp', '0016_carrito_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrito',
            options={'verbose_name': 'carrito', 'verbose_name_plural': 'carrito'},
        ),
        migrations.AlterField(
            model_name='carrito',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='carrito',
            table='carrito',
        ),
    ]
