# Generated by Django 4.2.11 on 2024-06-08 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DreamTravelapp', '0017_alter_carrito_options_alter_carrito_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='id_rol',
            field=models.ForeignKey(db_column='id_rol', default=1, on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.rol'),
        ),
    ]
