# Generated by Django 4.2.11 on 2024-06-08 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DreamTravelapp', '0018_alter_usuarios_id_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='id_rol',
            field=models.ForeignKey(db_column='id_rol', default='1', on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.rol'),
        ),
    ]
