# Generated by Django 4.2.11 on 2024-06-08 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DreamTravelapp', '0019_alter_usuarios_id_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinos',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.categorias'),
        ),
        migrations.AlterField(
            model_name='destinos',
            name='id_metodoPago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.metodopago'),
        ),
        migrations.AlterField(
            model_name='destinos',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
