# Generated by Django 4.2.11 on 2024-05-31 22:30

import DreamTravelapp.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodoPago', models.AutoField(primary_key=True, serialize=False)),
                ('nombrePago', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Metodos De Pago',
                'verbose_name_plural': 'Metodos de pagos',
                'db_table': 'metodo_pago',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(default='usuario', max_length=100)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'roles',
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('apellido_usuario', models.CharField(max_length=100)),
                ('passw', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(8)])),
                ('telefono', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('id_metodoPago', models.ForeignKey(db_column='id_metodoPago', on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.metodopago')),
                ('id_rol', models.ForeignKey(db_column='id_rol', default='1', on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id_nosotros', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_apellido', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('imagen', models.CharField(max_length=100)),
                ('id_rol', models.ForeignKey(db_column='id_rol', default='1', on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.rol')),
            ],
            options={
                'verbose_name': 'Nosotros',
                'verbose_name_plural': 'Nosotros',
                'db_table': 'nosotros',
            },
        ),
        migrations.CreateModel(
            name='Destinos',
            fields=[
                ('id_destino', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_Destino', models.CharField(max_length=150)),
                ('descripcion', models.TextField(default='descripcion')),
                ('image', models.TextField(default='imagen')),
                ('precio_Destino', models.DecimalField(decimal_places=2, max_digits=12, validators=[DreamTravelapp.models.positive_price_validator])),
                ('fecha_salida', models.DateTimeField()),
                ('cantidad_Disponible', models.IntegerField(default=12, validators=[DreamTravelapp.models.positive_viaje_validator])),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.categorias')),
                ('id_metodoPago', models.ForeignKey(db_column='id_metodoPago', on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.metodopago')),
            ],
            options={
                'verbose_name': 'Destino',
                'verbose_name_plural': 'Destinos',
                'db_table': 'destinos',
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=0, max_digits=3, validators=[DreamTravelapp.models.positive_price_validator])),
                ('id_destino', models.ForeignKey(db_column='id_destino', on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.destinos')),
                ('id_metodoPago', models.ForeignKey(db_column='id_metodoPago', on_delete=django.db.models.deletion.CASCADE, to='DreamTravelapp.metodopago')),
            ],
        ),
    ]
