# Generated by Django 5.0.6 on 2024-06-01 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DreamTravelapp', '0012_rol_alter_categorias_options_remove_nosotros_rol_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'roles'},
        ),
    ]
